[package]
name = "sprig"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/DISTREAT/sprig"
authors = ["DISTREAT"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
